#!/usr/bin/env bash

DOTFILES_DIRECTORY="${HOME}/dotfiles"
DOTFILES_GIT_REMOTE="git@github.com:shlikhota/dotfiles.git"

seek_confirmation() {
    printf "\n"
    echo "$@"
    read -p "Continue? (y/n) " -n 1 REPLY
    printf "\n"
}

is_confirmed() {
    if [[ "$REPLY" =~ ^[Yy]$ ]]; then
      return 0
    fi
    return 1
}

seek_confirmation "There will be installed xcode cli tools and nix. Do you want to proceed?"
if ! is_confirmed; then
    echo "Canceled."
    exit 0
fi

if ! command -v nix > /dev/null; then
    echo "Installing dependencies..."
    xcode-select --install
else
    echo "Dependencies have already been installed."
fi

if [[ ! -d ${DOTFILES_DIRECTORY} ]]; then
    echo "Cloning repository..."
    git clone ${DOTFILES_GIT_REMOTE} ${DOTFILES_DIRECTORY}
else
    echo "Dotfiles have already been cloned."
fi

cd ${DOTFILES_DIRECTORY}

if ! command -v nix > /dev/null; then
  echo "Installing nix..."
  curl --proto '=https' --tlsv1.2 -sSf -L https://install.determinate.systems/nix | sh -s -- install
else
  echo "Nix has already been installed."
fi

seek_confirmation "Do you want to apply nix configuration?"
if is_confirmed; then
    nix run nix-darwin -- switch --flake ${DOTFILES_DIRECTORY}#home
else
    echo "Configurations haven't been applied."
fi
