#!/bin/bash

DOTFILES_DIRECTORY="${HOME}/.dotfiles"
DOTFILES_TARBALL_PATH="https://github.com/shlikhota/dotfiles/tarball/master"
DOTFILES_GIT_REMOTE="git@github.com:shlikhota/dotfiles.git"

if [[ ! -d ${DOTFILES_DIRECTORY} ]]; then
    echo "Downloading dotfiles..."
    mkdir ${DOTFILES_DIRECTORY}
    # Get the tarball
    curl -fsSLo ${HOME}/dotfiles.tar.gz ${DOTFILES_TARBALL_PATH}
    # Extract to the dotfiles directory
    tar -zxf ${HOME}/dotfiles.tar.gz --strip-components 1 -C ${DOTFILES_DIRECTORY}
    # Remove the tarball
    rm -rf ${HOME}/dotfiles.tar.gz
fi

cd ${DOTFILES_DIRECTORY}

if ! command -v brew > /dev/null; then
  echo "Installing Homebrew..."
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
else
  echo "Homebrew already installed."
fi

ZSH_CUSTOM="$HOME/.oh-my-zsh/custom"

if [[ ! -e "${ZSH_CUSTOM}/themes/spaceship.zsh-theme" ]]; then
  echo "Installing spaceship theme oh-my-zsh..."
  git clone https://github.com/denysdovhan/spaceship-prompt.git "${ZSH_CUSTOM}/themes/spaceship-prompt" --depth=1
  ln -s "${ZSH_CUSTOM}/themes/spaceship-prompt/spaceship.zsh-theme" "${ZSH_CUSTOM}/themes/spaceship.zsh-theme"
else
  echo "Spaceship theme already installed."
fi

ln -sf "${DOTFILES_DIRECTORY}/.zshrc" "${HOME}/.zshrc"

seek_confirmation() {
    printf "\n"
    echo "$@"
    read -p "Continue? (y/n) " -n 1
    printf "\n"
}

is_confirmed() {
    if [[ "$REPLY" =~ ^[Yy]$ ]]; then
      return 0
    fi
    return 1
}

seek_confirmation "Do you want to apply nix configuration?"

if is_confirmed; then
  bash ./macos
  echo "MacOS settings updated. You have to restart the computer."
else
  echo "Skipped MacOS settings."
fi
